### ISSUE TITLE
Group Chat

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/xmppserver#24]
_From [Imberi...@googlemail.com](https://code.google.com/u/112458644166249821331/) on April 06, 2013 22:46:34_

To really be an alternative or better "the ultimate open mobile chat client" there need to be the possibility to do group chats. 
That means, that you can open a Group, invite users and those users are notified about the stuff written in the group, etc.
I would schedule that feature for the far future, version 4.0 or some kind of that, because this feature requires the following feature:
* send all data types
* do not download the files without permission ( if people in one group upload a hole bunch of stuff, this could really get nasty when relogin in after a big time span...)
* XMPP code base (therefore after version 3.0) to have easier developement
I think encryption between users would still work, wouldn't it?

by the way I will try to join developement of Kontalk in a week (after my examen). I've never programmed with the Android API (only read a bunch of stuff about it's conecpt), but I know how to work with Java and C++ with Qt, so I will try to help :)

_Original issue: http://code.google.com/p/kontalk/issues/detail?id=63_

**Comment by AntonioND** [comment]
Yeah, this is really important, I could replace my other chat apps if kontalk had group chats... You should give this top priority.

**Comment by daniele-athome** [comment]
Issued moved to kontalk/tigase-extension#5.
